# -*- coding: utf-8 -*-
"""funcionários

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109v8v6Ll9eC_lz2v-OLmi3eyA4RMPCnO
"""

#SISTEMA DE FUNCIONÁRIOS
import sqlite3

# Define o caminho do banco de dados
DB_PATH = "funcionarios.db"

def get_conn():
    """Cria uma conexão com o banco de dados SQLite."""
    return sqlite3.connect(DB_PATH)

def create_db():
    """Cria a tabela 'funcionarios' se ela não existir."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("""
    CREATE TABLE IF NOT EXISTS funcionarios (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        cargo TEXT NOT NULL,
        salario REAL NOT NULL DEFAULT 0.0
    );
    """)
    conn.commit()
    conn.close()

def input_float(prompt, minimo=None):
    """Função auxiliar para ler um número float do usuário."""
    while True:
        val = input(prompt).replace(",", ".").strip()
        try:
            x = float(val)
            if minimo is not None and x < minimo:
                print(f"Valor deve ser >= {minimo}.")
                continue
            return x
        except ValueError:
            print("Entrada inválida. Digite um número.")

def print_funcionario_row(row):
    """Formata e exibe uma linha (funcionário) do banco de dados."""
    _id, nome, cargo, salario = row
    print(f"[{_id}] {nome} | Cargo: {cargo} | Salário: R$ {salario:,.2f}")

def adicionar_funcionario():
    """Adiciona um novo funcionário ao banco de dados."""
    print("\n=== Adicionar Funcionário ===")
    nome = input("Nome do funcionário: ").strip()
    if not nome:
        print("O nome é obrigatório. Operação cancelada.")
        return

    cargo = input("Cargo: ").strip()
    if not cargo:
        print("O cargo é obrigatório. Operação cancelada.")
        return

    salario = input_float("Salário (R$): ", minimo=0.0)

    conn = get_conn()
    cur = conn.cursor()
    try:
        cur.execute("""
            INSERT INTO funcionarios (nome, cargo, salario)
            VALUES (?, ?, ?);
        """, (nome, cargo, salario))
        conn.commit()
        print("Funcionário adicionado com sucesso!")
    except sqlite3.Error as e:
        print(f"Erro ao adicionar funcionário: {e}")
        conn.rollback()
    finally:
        conn.close()

def listar_funcionarios():
    """Lista todos os funcionários cadastrados, ordenados por nome."""
    print("\n=== Funcionários Cadastrados ===")
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("SELECT id, nome, cargo, salario FROM funcionarios ORDER BY nome;")
    rows = cur.fetchall()
    conn.close()

    if not rows:
        print("Nenhum funcionário cadastrado.")
        return

    for r in rows:
        print_funcionario_row(r)

def buscar_funcionario():
    """Busca funcionários cujo nome contenha o termo digitado."""
    print("\n=== Buscar Funcionário por Nome ===")
    termo = input("Buscar por nome (contém): ").strip()
    if not termo:
        print("Termo de busca vazio.")
        return

    conn = get_conn()
    cur = conn.cursor()
    cur.execute("""
        SELECT id, nome, cargo, salario
        FROM funcionarios
        WHERE nome LIKE ?
        ORDER BY nome;
    """, (f"%{termo}%",)) # Usa % para "conter"

    rows = cur.fetchall()
    conn.close()

    if not rows:
        print("Nenhum funcionário encontrado.")
        return

    print(f"\nResultados para '{termo}':")
    for r in rows:
        print_funcionario_row(r)

def calcular_media_salarial():
    """Calcula e exibe o salário médio de todos os funcionários."""
    print("\n=== Média Salarial ===")
    conn = get_conn()
    cur = conn.cursor()

    cur.execute("SELECT COALESCE(AVG(salario), 0.0), COUNT(id) FROM funcionarios;")
    resultado = cur.fetchone()
    conn.close()

    media, contagem = resultado

    if contagem == 0:
        print("Não há funcionários cadastrados para calcular a média.")
    else:
        print(f"Total de funcionários: {contagem}")
        print(f"A média salarial de todos os funcionários é: R$ {media:,.2f}")

def menu():
    """Exibe o menu principal e gerencia a navegação do usuário."""
    while True:
        print("\n=== SISTEMA DE FUNCIONÁRIOS ===")
        print("1) Adicionar funcionário")
        print("2) Listar funcionários")
        print("3) Buscar funcionário por nome")
        print("4) Calcular média salarial")
        print("0) Sair")

        op = input("Escolha: ").strip()

        if op == "1":
            adicionar_funcionario()
        elif op == "2":
            listar_funcionarios()
        elif op == "3":
            buscar_funcionario()
        elif op == "4":
            calcular_media_salarial()
        elif op == "0":
            print("Até mais!")
            break
        else:
            print("Opção inválida. Tente novamente.")


if __name__ == "__main__":
    create_db()  
    menu()
